### PR TITLE
Be sure to closedir before return

### PR DESCRIPTION
**Pull request by strassek**
This will be a memory leak if we fail to close the dir

Jira: GSE-1595
Test: Build and boot on Android

Signed-off-by: Kevin Strasser <kevin.strasser@intel.com>

### CODE REVIEW

**Comment by kalyankondapally** [comment]
@strassek Can we send this to dridevel mailing list for review ?

**Comment by tpalli** [comment]
this seems to be already fixed in upstream

**Comment by kalyankondapally** [comment]
probably time to rebase.

**Comment by kalyankondapally** [comment]
@tpalli I dont see the commit, can you point me to the right one for cherrypicking it

**Comment by tpalli** [comment]
Not sure how feasible it is to cherrypick but it is 0ca03a4087a550646de7f26b6b53a932e8546474

**Comment by tpalli** [comment]
hah yeah, actually commit bb45ce4e3ac751315bfd7fbfd9e1425bf515ec0d removed the closedir and thus resulted this regression ... so this is not in upstream after all .. maybe good to mention that

**Comment by strassek** [comment]
ok, I'll look at pushing this upstream

**Comment by strassek** [comment]
Patch landed upstream, ready for cherry pick or rebase

**Comment by kalyankondapally** [comment]
rebased to latest free desktop.

**Pull request closed without merging**
